### ISSUE TITLE
feature request: (option to) hide your own pronouns

### ISSUE THREAD

**Issue by EmeraldSnorlax** [cyyynthia/pronoundb-powercord#10]
when taking screenshots of conversations on discord, i dont always want to reveal my pronouns (e.g. conversations with people i know in real life). however, they are visible in screenshots, which gets annoying to have to remove w/ devtools before taking a screenshot

this is probably quite a niche case, eh?

**Comment by cyyynthia** [comment]
That's a perfectly valid case, and a switch for that has been implemented in e54b70562bc43cd7ceb587fa9c3d3f23ab0b6429
