### ISSUE TITLE
[Bug] TypeError: t.isForumPost is not a function

### ISSUE THREAD

**Issue by spinfal** [cyyynthia/pronoundb-powercord#13]
When installing and enabling the plugin, I get this error in the console:
![Plugin Console Error](https://cdn.spin.rip/r/1a51c378-26b3-44ba-9a54-c5c2f0420756.png)

And this error in the Plugin settings:
![Plugin Settings Error](https://cdn.spin.rip/r/fc67e7c8-a17c-4833-a1bd-1e596cb4cbbb.png)

Device info:
- Canary 118637 (13cc77b)
- Host 1.0.45
- Windows 11 (21H2, 22000.556)
- Powercord v2 (8b99354)
- Plugin version v2.1.1

**Comment by asportnoy** [comment]
Got the same error

Canary 118649 (21b0ded)
Host 0.0.283
OS X 10.15.7 (21.4.0)
Powercord v2 (8b99354)
Plugin version v2.1.1

**Comment by xPolar** [comment]
Having the same error.
Canary 119702 (55c55eb) 
Host 1.0.45 | OpenAsar 8203724 
Windows 10 64-Bit (10.0.22000)
Powercord v2 (8b99354)
