### ISSUE TITLE
Manually save people's pronouns

### ISSUE THREAD

**Issue by cyyynthia** [cyyynthia/pronoundb-powercord#3]
For people who don't have a PDB account, so you can still save their pronouns somewhere. If they open an account, the pronouns returned by the API should take priority

**Comment by randomdiscorduser** [comment]
Would also be cool to see support for per-guild gender roles, being able to change those roles through the settings.

**Comment by cyyynthia** [comment]
> Would also be cool to see support for per-guild gender roles, being able to change those roles through the settings.

I really don't know what you mean by this.
