### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by randomdiscorduser** [cyyynthia/pronoundb-powercord#4]
![Screen Shot 2021-04-18 at 3 24 20 PM](https://user-images.githubusercontent.com/81717531/115159761-47616c80-a05a-11eb-9ad9-4468313af8a8.png)

**Comment by cyyynthia** [comment]
I can't seem to be able to reproduce the issue. Does it still happen after a reload? If so, what plugins do you have installed?

**Comment by randomdiscorduser** [comment]
it happens randomly and it is hard to consistently reproduce. I have a lot of plugins, here's a list of their names
```
% ls
Blanker					pc-rpc
Custom-User-Tags			pc-sdk
In-app-notifs				pc-settings
NSFW-tags				pc-spotify
SnowflakeInfo				pc-tags
alias					pc-updater
badges-everywhere			permission-viewer
bdCompat				powercalc
better-folders				powerclock
better-replies				powercord-auto-collapse-folders
better-status-indicators		powercord-brainfuck
betterfriends				powercord-devcommands
bored-powercord-plugin			powercord-emoji-url-viewer
bot-tag-in-autocomplete			powercord-guild-list-order-shortcuts
bubble-wrap				powercord-message-tooltips
channel-typing				message-link-embed
check-site				powercord-ownertag
copy-avatar-url				powercord-plugin-updater
custom-timestamps			powercord-sendtochannel
discord-bio				powercord-server-info
discord-richpresence			powercord-tile-channels
discord-status				powercord-weather
edited-anywhere				powermath
eval-plugin				pronoundb-powercord
image-tools				quick-toggler
lyrics					quickstar
minesweeper				relationship-notifier
multitask				remind-me
mutuals-quick-ban			rich-embeds
nekos-dot-life				rolecolor-everywhere
pc-clickableEdits			scrollable-autocomplete
pc-codeblocks				smart-typers
pc-commands				text-react
pc-connections				theme-toggler
pc-docs					unread-count-badges
pc-emojiUtility				urban
pc-hastebin				user-details
pc-heygirl				view-raw
pc-i18n					virus-checker
pc-lmgtfy				vpc-shiki
pc-mock					webhook-tag
pc-moduleManager			who-reacted
pc-notices				wpm
```

**Comment by randomdiscorduser** [comment]
a decent amount of those are disabled but thats just an ls of the plugin folder

**Comment by Wolfkid200444** [comment]
Ive been able to reproduce this issue multiple time 

https://user-images.githubusercontent.com/32025746/149561519-3241b68e-27b9-4540-9e9d-e0b14a3597a3.mp4

**Comment by RagdollClash** [comment]
Copy-pastting from the other issue:

This seems to happen whenever I hover over the preview in settings.


https://user-images.githubusercontent.com/15317421/151683511-a671d954-31ce-4499-8528-4fc474e57d38.mp4

**Comment by Leo40Git** [comment]
Can confirm it seems to error when hovered over.

https://user-images.githubusercontent.com/7997354/152050406-3b06a8f3-47c5-415c-a90c-2ff26b1562cc.mp4

**Comment by SkySpnc** [comment]
Also happens on hover here

![DiscordCanary_DqZX3LiqoD](https://user-images.githubusercontent.com/83870752/152615878-5cb1e3f2-4382-44d0-b1bf-95fdc1b70d4e.gif)
