### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by asportnoy** [cyyynthia/pronoundb-powercord#5]
I turned off "Show in chat" in the settings, but the pronouns are still showing in the chat. Seems to apply to other locations as well.

Powercord v2 (f876037)
Plugin v2.1.0

**Comment by cyyynthia** [comment]
Can't reproduce, settings do apply as expected on my end

**Comment by asportnoy** [comment]
For some reason it didn't actually save the setting when I tried it the first time. I disabled and re-enabled the plugin and changed the setting again and it's now working. Thanks!
