### ISSUE TITLE
Minor suggestion maybe for compact mode

### ISSUE THREAD

**Issue by mrchillington** [cyyynthia/pronoundb-powercord#6]
Maybe a space or some sort of separation between the chosen pronoun and the message in compact mode.

**Comment by cyyynthia** [comment]
I transferred the issue to the proper repository then; cyyynthia/pronoundb.org is only tracking the pronoundb.org website & api as well as the browser extension, not other integrations such as this plugin

**Comment by mrchillington** [comment]
That makes a lot more sense 😄
